import express from "express";
import { verifyToken } from "../middleware/auth.middleware.js";
import { sendMessage } from "../controller/conversationController.js";
import { fetchConversations } from "../controller/fetchConversations.js";
import { fetchAllConversation } from "../controller/fetchAllConversation.js";
import { changeStatus } from "../controller/changeStatus.js";
const chatRouter = express.Router();
chatRouter.post("/send",verifyToken,sendMessage);
chatRouter.get("/conversations/:userId",verifyToken,fetchConversations);
chatRouter.get("/get-all-conversation",verifyToken,fetchAllConversation);
chatRouter.post("/change-status-conversation/:idConversation",verifyToken,changeStatus);
export default chatRouter;